### ISSUE TITLE
当前版本的取消“科研”“委托”“收获”的办法？

### ISSUE THREAD

**Issue by NamecNull** [foxwhite25/AzurLaneAutoScriptThatWorks#13]
### 你的功能请求是否与问题有关？

:\AzurLaneAutoScript\module\config
     
  def force_enable(tasks):
            for task in tasks:
                enable = deep_get(self.data, keys=f'{task}.Scheduler.Enable', default=None)
                if enable is not None and not enable:
                    logger.warning(f'Task {task} is force to enable')
                    self.modified[f'{task}.Scheduler.Enable'] = True

        force_enable(['Commission', 'Research', 'Reward'])

  "type": "lock",
       

  # Override arguments
        for arg, value in self.overridden.items():
            super().__setattr__(arg, value)
        # for arg, value in self.overridden.items():
        #     super().__setattr__(arg, value)

        for arg, value in kwargs.items():
            self.overridden[arg] = value
            super().__setattr__(arg, value)
        pass
        # for arg, value in kwargs.items():
        #     self.overridden[arg] = value
        #     super().__setattr__(arg, value)

都关闭了 还是无法去除，现在好像还有强制自动更新

现在应该如何操作呢？

### 解决方案

当前版本的取消“科研”“委托”“收获”的办法

**Comment by foxwhite25** [comment]
由于此工具会自动更新，作者下一次提交commit后，再次运行程序会被替换回最新版本。
因此，可以修改这个文件：

> .\config\deploy.yaml

第6行，原本为
`Repository: https://github.com/LmeSzinc/AzurLaneAutoScript`
修改为
`Repository: https://github.com/foxwhite25/AzurLaneAutoScriptThatWorks`
**如果不信任此仓库或者将来寄了，你也可以自己创建一个fork**

再打开Alas.exe即可。

本fork修改过的内容可以在这看到 https://github.com/LmeSzinc/AzurLaneAutoScript/compare/master...foxwhite25:AzurLaneAutoScriptThatWorks:master#files_bucket 。

**Comment by foxwhite25** [comment]
不过我很好奇你是怎么找到这了，这作者删评删issue都删光了

**Comment by NamecNull** [comment]
群里有发这条issue，在里面找到的。不过现在的话如果修改了代码&nbsp; 在大世界中的漩涡和红boss进去后将出现镜头位移错误的报错 ，估计也是作者留下的暗桩，这个能修复下吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月10日(星期三) 晚上10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [foxwhite25/AzurLaneAutoScriptThatWorks] 当前版本的取消“科研”“委托”“收获”的办法？ (Issue #13)





 
不过我很好奇你是怎么找到这了，这作者删评删issue都删光了

**Comment by foxwhite25** [comment]
> 群里有发这条issue，在里面找到的。不过现在的话如果修改了代码&nbsp; 在大世界中的漩涡和红boss进去后将出现镜头位移错误的报错 ，估计也是作者留下的暗桩，这个能修复下吗？

有需要可以开个新的issue，但我自己运行并没有遇到这个问题

**Comment by NamecNull** [comment]
请问能将您使用的 alas.json配置发我一份吗？ 想看看是否是我的设置出了问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月29日(星期六) 上午9:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [foxwhite25/AzurLaneAutoScriptThatWorks] 当前版本的取消“科研”“委托”“收获”的办法？ (Issue #13)





  
群里有发这条issue，在里面找到的。不过现在的话如果修改了代码&nbsp; 在大世界中的漩涡和红boss进去后将出现镜头位移错误的报错 ，估计也是作者留下的暗桩，这个能修复下吗？
  
有需要可以开个新的issue，但我自己运行并没有遇到这个问题

**Comment by foxwhite25** [comment]
https://gist.github.com/foxwhite25/56a68497de866e78600e478443abd265
